kind: pipeline
type: docker
name: screenshotOverview

steps:
  - name: screenshotOverview
    image: nextcloudci/android:android-49
    environment:
      LOG_USERNAME:
        from_secret: LOG_USERNAME
      LOG_PASSWORD:
        from_secret: LOG_PASSWORD
    commands:
      - scripts/screenshots/generateScreenshotHtml.sh
      - scripts/screenshots/uploadScreenshotHtml.sh $LOG_USERNAME $_LOG_PASSWORD

trigger:
  event:
    - push
    - pull_request
