name: Analysis

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    android_lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                    java-version: 1.8
            - run: ./gradlew lint
            - uses: yutailang0119/action-android-lint@v1.0.2
              with:
                    xml_path: build/reports/lint-results.xml
    analysis:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Run analysis
                shell: bash
                env:
                    GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
                    GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
                run: |
                    mkdir -p $HOME/.gradle
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > $HOME/.gradle/gradle.properties
                    scripts/analysis/analysis-wrapper.sh $GIT_USERNAME $GIT_TOKEN "master" $LOG_USERNAME $LOG_PASSWORD $DRONE_BUILD_NUMBER $DRONE_PULL_REQUEST
